[MC-43] Create logic component checkbox
feelsantiago/mesa-computaria pull request #57
Opened 2022-04-19 22:04 UTC by EvertonDuarteGuimaraes

# Feature/Issue Description
- add getters/setters
- add click event
- add Component super class with enable/disabled method and required propriety
- add heritage for checkbox and dropdown
- change checkbox HTML
- change checkbox SCSS classes

# Changes Summary
- add checkbox component JS file
- add new Checkbox component class
- add checkbox component tests

# How Has This Been Tested?
- Run server
- Go to components, find checkbox.component.js file
- Go to main.js
- Use any checkbox methods available listed in CheckboxComponent class.

2022-04-20 11:46 UTC, feelsantiago requested changes

2022-04-20 11:46 UTC, feelsantiago commented on src/components/checkbox.component.js
> +    setChecked() {
No need to add set prefix

2022-04-20 11:46 UTC, feelsantiago commented on src/components/checkbox.component.js
> +    setUnchecked() {
No need to set prefix

2022-04-20 11:46 UTC, feelsantiago commented on src/components/checkbox.component.js
> +            this.checked = this._checkbox.is(':checked');
This code is repeated 3 times.

2022-04-20 20:13 UTC, EvertonDuarteGuimaraes commented on src/components/checkbox.component.js
> +    setChecked() {
Fixed

2022-04-20 20:13 UTC, EvertonDuarteGuimaraes commented on src/components/checkbox.component.js
> +    setUnchecked() {
Fixed

2022-04-20 20:13 UTC, EvertonDuarteGuimaraes commented on src/components/checkbox.component.js
> +            this.checked = this._checkbox.is(':checked');
Now it's a method

2022-04-22 18:23 UTC, RodrigoSoaresNascimento approved these changes, later dismissed
Great!

2022-04-22 22:20 UTC, tvps20 submitted a review, later dismissed

2022-04-22 23:27 UTC, RodrigoSoaresNascimento approved these changes

2022-04-22 23:29 UTC, tvps20 approved these changes

2022-04-22 23:39 UTC, feelsantiago approved these changes

2022-04-22 23:42 UTC, merged