[MC-17] Create Date Component Input
feelsantiago/mesa-computaria pull request #60
Opened 2022-04-26 17:52 UTC by pedroemanuel42

# Feature/Issue Description
This PR added a date input component behind password input component.

# Changes Summary
- Added new input date;
- Refactored and re-used input password CSS creating standard configs;

# How Has This Been Tested?
To test this new component, i went into localhost and checked the input.

# Images (Opcional)
![image](https://user-images.githubusercontent.com/99288851/165361671-b990c10a-865e-4a4a-83fe-243eba56be9a.png)
![image](ht
![image](https://user-images.githubusercontent.com/99288851/165361745-5935fa34-4d3c-4880-952a-0a297469207c.png)
tps://user-images.githubusercontent.com/99288851/165361708-31e73b21-ebba-42f5-acb6-887928f72d0f.png)
![image](https://user-images.githubusercontent.com/99288851/165361845-7b6a199b-0262-4adc-8dd6-5b741ac86cd7.png)

2022-04-26 19:09 UTC, EvertonDuarteGuimaraes approved these changes, later dismissed

2022-04-28 12:19 UTC, tvps20 reviewed
Why is this component not aligned with the one above?
![image](https://user-images.githubusercontent.com/23269934/165750288-4245d212-1cd1-4f39-a8ba-180aa8f4dfc2.png)

2022-04-28 12:22 UTC, tvps20 commented on src/pages/components/index.html
> +        <div class="date-box" id="date">
Why the date-box is in the div:row-password?

2022-04-29 10:50 UTC, tvps20 submitted a review, later dismissed

2022-04-29 11:26 UTC, feelsantiago requested changes

2022-04-29 11:26 UTC, feelsantiago commented on src/assets/scss/input-date.scss
> +.next-game {
Why is a `next-game` to a date component?

2022-04-29 11:26 UTC, feelsantiago commented on src/pages/components/style.scss
> +    //Space to put away from other components (optional)
If a css is optional it should be a new class so the user can decide if want to add or not.

2022-04-29 16:33 UTC, RodrigoSoaresNascimento approved these changes, later dismissed
Great!

2022-05-02 10:34 UTC, feelsantiago approved these changes

2022-05-02 12:30 UTC, tvSantiago approved these changes

2022-05-02 12:31 UTC, tvps20 approved these changes

2022-05-02 21:26 UTC, merged